# Generated by Django 3.0.4 on 2020-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiblockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mine',
            field=models.BooleanField(default=False),
        ),
    ]
